# Generated by Django 4.1.1 on 2022-09-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=75)),
                ('quentinha', models.JSONField()),
            ],
        ),
    ]
