# Generated by Django 4.1.1 on 2022-10-25 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refeitorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('aluno_faltante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refeitorio.aluno')),
            ],
        ),
    ]
