# Generated by Django 4.1.1 on 2022-10-25 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refeitorio', '0003_alter_falta_aluno_faltante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falta',
            name='aluno_faltante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refeitorio.aluno'),
        ),
    ]
