# Generated by Django 4.1.1 on 2022-11-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeitorio', '0005_falta_justificativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='falta',
            name='arquivo',
            field=models.FileField(default=2, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
