# Generated by Django 4.1.1 on 2022-11-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeitorio', '0008_alter_falta_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falta',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
