# Generated by Django 4.1.1 on 2022-11-30 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeitorio', '0009_alter_falta_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(null=True)),
                ('data', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
