# Generated by Django 4.1.1 on 2022-11-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refeitorio', '0010_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='comentador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='refeitorio.aluno'),
        ),
    ]
